### ISSUE TITLE
Operatoren fehlen

### ISSUE THREAD

**Issue by FlorianAdler** [lkempf/AlgebraStroppel#1]
Auf Seite 26, Beispiel 7.4 fehlt mehrfach ein großer Operator (Produkt oder so?). "Fehlen" im Sinne von "weißer Platz, wo ein Operator sein sollte".

Ich glaube, das ist noch an einigen anderen Stellen so, bin aber gerade zu faul, die rauszusuchen.

**Comment by amesgen** [comment]
Hmm, meinst du die Gleichung zur Definition der Auswertungsabbildung? Da sind die Pfeile nicht ganz schön untereinander ausgerichtet (habe das gerade lokal gefixt). Sonst sehe ich nicht, wo ein Operator fehlen könnte. Kannst du noch ein Beispiel angeben?

und btw: Das Skript hat noch ein paar größere Änderungen vor sich. So ist die Nummerierung noch nicht ganz so, wie es wünschenswert wäre, "Ringe" sollte wohl kein Unterpunkt von "Gruppen" sein und es gibt noch keine gute Referenzierung auf Theorem-artige Dinge (Lukas kämpft derzeit noch etwas mit `cleveref`...).

Vielen Dank aber für jede Rückmeldung!

**Comment by lkempf** [comment]
@FlorianAdler Ich hab mir das gerade auch mal angeschaut und kann es zumindest im travis-output nicht erkennen. Aber ich komm gleich mal rüber und schau es mir da an.

**Comment by lkempf** [comment]
Anzeigebug
