### ISSUE TITLE
Langer Einbettungspfeil

### ISSUE THREAD

**Issue by amesgen** [lkempf/AlgebraStroppel#2]
Uns fehlt ein langer Einbettungspfeil/injektiver Pfeil (ganz grob so: ↪). Ich habe trotz Suche und Detexify nichts Sinnvolles finden können. Falls irgendjemandem also `\hookrightarrow` in "lang" über den Weg läuft, bitte melden.

**Comment by lkempf** [comment]
Es gibt jetzt `\longhookarrow` (Package `old-arrows`).
